"""
shared.types
============
All Pydantic BaseModel classes shared by two or more ARIA packages.

This is the single source of truth for cross-cutting data models.
Never redefine these in another module — always import from here.

Usage::

    from shared.types import PlanStep, EpisodicMemory, Citation
    from shared import PlanStep, EpisodicMemory  # shorthand also works
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class PlanStep(BaseModel):
    """A single step in an execution plan generated by the Planner node."""

    step_number: int
    action: str
    tool: str
    tool_params: Dict[str, Any] = Field(default_factory=dict)
    expected_output: str
    fallback_action: str
    can_parallelize: bool = False


class ToolCallRecord(BaseModel):
    """Record of a tool call that was dispatched."""

    tool_name: str
    input: Dict[str, Any]
    timestamp: str = ""


class ToolOutputRecord(BaseModel):
    """Result of a single tool call execution."""

    tool_name: str
    input: Dict[str, Any] = Field(default_factory=dict)
    output: Any = None
    latency_ms: int = 0
    success: bool = True
    error_message: Optional[str] = None


class ReflectionScores(BaseModel):
    """Quality scores from the ReflectionAgent."""

    relevance: float
    groundedness: float
    completeness: float
    critique: str = ""
    passed: bool = False


class Citation(BaseModel):
    """An inline source citation extracted from a response."""

    text: str
    source_url: str = ""
    source_title: str = ""
    position: int = 0


class ErrorEntry(BaseModel):
    """A logged error from any component during a request."""

    timestamp: str
    component: str
    error: str
    context: str = ""


class EpisodicMemory(BaseModel):
    """A single memory entry from the episodic memory store."""

    memory_id: str
    content: str
    importance_score: float
    category: str
    created_at: str
    last_accessed: str
    access_count: int = 0
    decay_rate: float = 0.005


class MemoryWrite(BaseModel):
    """A memory entry to be written to the episodic store."""

    content: str
    category: str
    importance_score: float
    user_id: str
    session_id: str


class ProcessedOutput(BaseModel):
    """Result from the ResponsibleAI output processing pipeline."""

    cleaned_response: str
    citations: List[Citation] = Field(default_factory=list)
    hallucination_flags: List[str] = Field(default_factory=list)
    pii_redacted_in_logs: bool = True
